version: 2.1
orbs:
  pack: buildpacks/pack@0.2.2
  ruby: circleci/ruby@1.1.2

references:
  specs: &specs
    run:
      name: Run test suite
      command: PARALLEL_SPLIT_TEST_PROCESSES="4" IS_RUNNING_ON_CI=1 bundle exec parallel_split_test spec/

  standardrb: &standardrb
    run:
      name: Linting
      command: bundle exec standardrb

jobs:
  specs:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: xlarge
    steps:
      - checkout
      - pack/install-pack:
          version: 0.16.0
      - ruby/install-deps
      - <<: *specs
  standardrb:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - ruby/install-deps
      - <<: *standardrb

workflows:
  version: 2
  build:
    jobs:
      - specs
      - standardrb

